In [115]:
# creating arrays

import numpy as np

a = np.array([2,3,4,6])

print(np.zeros(a.shape))

print(np.ones(a.shape))

print(np.full((a.shape),3)) # np.full(shape,element to full)
print("\n")
print(np.eye(3,dtype="int")) # np.eye(no.of rows) creates Identity matrix
print("\n")
v1 = np.arange(1,10,2) # np.arange(start, stop, size.ofsteps)
print(v1)

print(np.linspace(1,10,3)) # np.linspace(start, stop, no. of steps)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[3 3 3 3]


[[1 0 0]
 [0 1 0]
 [0 0 1]]


[1 3 5 7 9]
[ 1.   5.5 10. ]


In [116]:
# numpy.random.random() is one of the function for doing random sampling in numpy. 
# It returns an array of specified shape 
# and fills it with random floats in the half-open interval [0.0, 1.0).

print(np.random.random((2,3))) # np.random.random(size)

# normally distributed random values

print(np.random.normal(1,5,10)) # np.random.normal(mean, stdev, size or shape) displays random values in gaussian distribution

print(np.random.randint(2,20,(2,2))) # np.random.randint(low, high, size or shape of matrix)

#create an uninitialized array of 3 elements
a = np.empty(3)
print(a)

print(np.array([2,4.6,6]))

#Nested sequences

l1=[2,3,4]
l2=[1,2,3]
a=np.array((l1,l2))
print(a)

[[0.3170819  0.81426198 0.64971665]
 [0.70422824 0.23472242 0.53110191]]
[ 2.77910078  2.849372   -6.93000204 -4.83176476  0.46859211  9.36901298
  0.59530965  1.49657674  3.21242086  2.15207558]
[[ 3 14]
 [18 16]]
[ 1.   5.5 10. ]
[2.  4.6 6. ]
[[2 3 4]
 [1 2 3]]


In [ ]:
import numpy as np
# Type casting

a = np.array([1,2,3],dtype = "int")
print("The array of integer type: ",a)
a2 = a.astype(float)
print("The array after Type casting : ",a2

In [4]:
# arithmetic operations

a = np.array([[1,2,3],[4,5,6]])
print(a+a)
print(a-10)
print(a*10)
print(a/10)


[[ 2  4  6]
 [ 8 10 12]]
[[-9 -8 -7]
 [-6 -5 -4]]
[[10 20 30]
 [40 50 60]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [7]:
# matrix multiplication using diff functions

a = np.array([[1,2,3],[4,5,6]]) # 2*3
b = np.array([[3,2],[6,4],[1,2]]) # 3*2

print("a@b is : \n",a@b)
print("np.matmul(a,b) is: \n",np.matmul(a,b))
print("np.dot(a,b) is: \n",np.dot(a,b))


a@b is : 
 [[18 16]
 [48 40]]
np.matmul(a,b) is: 
 [[18 16]
 [48 40]]
np.dot(a,b) is: 
 [[18 16]
 [48 40]]


In [21]:
#Basic Indexing and Slicing#

# array slices are views on the original array
#This means that the data is not copied, and any modifications
#to the view will be reflected in the source array.


a = np.array([[1,2,3],[4,5,6]])
print(a[0,1])
temp = a[0].copy() # used for shallow copying
print(temp)

# 1d array indexing

a = np.array([1,2,44,32])
print(a)
print('---------')
print(a[0])
print(a[2])

# 2d array indexing

a = np.array([[1,2,3],[4,5,6]])
print(a)
print('********')
print(a[0,1])
print(a[1,2])

# 3d array indexing

a = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[3,5,4],[3,2,1],[0,9,8]]])
print(a)
print('--------')
print("a[0,0,2] is : ",a[0,0,2])

2
[1 2 3]
[ 1  2 44 32]
---------
1
44
[[1 2 3]
 [4 5 6]]
********
2
6
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 5 4]
  [3 2 1]
  [0 9 8]]]
--------
a[0,0,2] is :  3
[[3 5 4]
 [3 2 1]
 [0 9 8]]


In [16]:
#slicing
# There are many ways you may want to select a subset of your data or individual elements

a = np.arange(1,10)
print(a)

#if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
#propagated to the entire selection

a2 = a[3:7] # index[start:stop-1]
print(a2)

print(a,a2)
a2[:] = 33
print(a2,a)

[1 2 3 4 5 6 7 8 9]
[4 5 6 7]
[1 2 3 4 5 6 7 8 9] [4 5 6 7]
[33 33 33 33] [ 1  2  3 33 33 33 33  8  9]


In [31]:
a=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print(a)
print(a[:2,:1])
print(a[1,:2])
print(a[2,:1])
print('----')

b=a[:,1]
print("columns")
print(b,b.size, b.shape)
c=a[:,:2]
print(c,c.size, c.shape,c.ndim)
c=a[:,2]
print(c,c.size, c.shape,c.ndim)
d=a[:,2:]
print(d,d.size,d.shape,d.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]]
[4 5]
[7]
----
columns
[2 5 8] 3 (3,)
[[1 2]
 [4 5]
 [7 8]] 6 (3, 2) 2
[3 6 9] 3 (3,) 1
[[3]
 [6]
 [9]] 3 (3, 1) 2


In [39]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will'])

data = np.random.randn(5, 4) 
# array of defined shape filled with random floating point samples from std normal dist

print(names,names.dtype,data,data.dtype)
print(names == 'Bob')
print(data[names=='Bob'])
print(names != 'Bob')

mask = (names == 'Bob') | (names == 'Will')
print('mask=   ',mask)

print(data[data<0])

#set all of the negative values in data to 0 we need only do

data[data<0]=0
print(data)
#The boolean array must be of the same length as the axis it’s indexing

['Bob' 'Joe' 'Will' 'Bob' 'Will'] <U4 [[-1.93605614 -0.26040153  0.73140743  2.1328136 ]
 [ 0.41665114 -1.21666993 -1.08323935  0.11922547]
 [ 0.82499181  0.48003177 -0.16985182  0.70259408]
 [ 0.68678545 -0.62298096 -1.06772088  0.60560198]
 [ 0.51459813  2.01898141 -0.52056716  0.66084522]] float64
[ True False False  True False]
[[-1.93605614 -0.26040153  0.73140743  2.1328136 ]
 [ 0.68678545 -0.62298096 -1.06772088  0.60560198]]
[False  True  True False  True]
mask=    [ True False  True  True  True]
[-1.93605614 -0.26040153 -1.21666993 -1.08323935 -0.16985182 -0.62298096
 -1.06772088 -0.52056716]
[[0.         0.         0.73140743 2.1328136 ]
 [0.41665114 0.         0.         0.11922547]
 [0.82499181 0.48003177 0.         0.70259408]
 [0.68678545 0.         0.         0.60560198]
 [0.51459813 2.01898141 0.         0.66084522]]


In [44]:
# fancy indexing :
# it allows to use an array of indices to access multiple array elemets at once

a = np.array([1,232,3,5,666])
# print(a[1,2,3]) returns error

print(a[[1,2,3]]) #np.argsort sorts the elements and return their sorted indices
print(a[np.argsort(a)])

#Multiple index arrays - selects a one dimensional array of elements corresponding to each tuple of indices.
#regardless of no of dimensions of the array, the result is one-dimensional

a= np.arange(32).reshape(8,4)

print(a)
print('\n\n -----')
print(a[[1,5,7,2],[0,3,1,2]]) # [1,5,7,2] rows [0,3,1,2] colum eles are returned


[232   3   5]
[  1   3   5 232 666]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


 -----
[ 4 23 29 10]


In [120]:
#slicing

s = np.array([1,2,3,4,66,51])  # 1d array slicing
s[2:5:1]  # x[i : j-1: k]

#both are same

print(s[::-1])
print(s[:])

print(s[1:-1])

print("\n")

[51 66  4  3  2  1]
[ 1  2  3  4 66 51]
[ 2  3  4 66]




In [46]:
#transposing arrays and swapping Axes
#transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything
#Arrays have the transpose method and also the special T attribute. used for inner matrix product
import numpy as np
a=np.arange(15).reshape((3,5))
print('matrix= \n',a)

print('transpose=\n ',a.T)


matrix= 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
transpose=
  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [47]:
a1=np.arange(18).reshape((3,6))
print('new mat= ',a1)
print('dot product\n')
print(np.dot(a1.T,a1))
print('product')
print(a1@a1.T)

new mat=  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
dot product

[[180 198 216 234 252 270]
 [198 219 240 261 282 303]
 [216 240 264 288 312 336]
 [234 261 288 315 342 369]
 [252 282 312 342 372 402]
 [270 303 336 369 402 435]]
product
[[  55  145  235]
 [ 145  451  757]
 [ 235  757 1279]]


In [55]:
# matrix operations

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1],[2,2],[3,2]])
c= np.array([[1,3,5],[7,9,2],[4,6,8]])

print("np.dot(a,b): ",np.dot(a,b))
print("np.transpose(a): ",np.transpose(a))
print("The inverse of a is: np.linalg.inv(c) : \n")
print(np.linalg.inv(c))
print("The det of c is np.linalg.det(c): \n")
print(np.linalg.det(c))



np.dot(a,b):  [[14 11]
 [32 26]]
np.transpose(a):  [[1 4]
 [2 5]
 [3 6]]
The inverse of a is: np.linalg.inv(c) : 

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]
The det of c is np.linalg.det(c): 

-54.00000000000001


In [76]:
# array manipulation routines

a = np.array([1,1,2,2,33])
print(np.insert(a,3,4))

a = np.array([[1,2,4],[3,4,5],[1,2,2]])
print(a)
print("\n")


# np.insert(array, index, element or array to insert)

print(np.insert(a,1,22,axis=1)) # axis=1 column wise and axis = 0 row wise
print('-----')
print(np.insert(a,1,[0,23,90],axis =0))

print('-------')
print(np.insert(a,[1,2],[0,23,90],axis =0))

[ 1  1  2  4  2 33]
[[1 2 4]
 [3 4 5]
 [1 2 2]]


[[ 1 22  2  4]
 [ 3 22  4  5]
 [ 1 22  2  2]]
-----
[[ 1  2  4]
 [ 0 23 90]
 [ 3  4  5]
 [ 1  2  2]]
-------
[[ 1  2  4]
 [ 0 23 90]
 [ 3  4  5]
 [ 0 23 90]
 [ 1  2  2]]


In [81]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[11,22],[33,44],[55,66]])

d=np.append(a,b)
print(d)
print('------')
z=np.concatenate((a,b)) # joins the sequence of arrays along the existing axis
print(z)

[ 1  2  3  4  5  6 11 22 33 44 55 66]
------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 22]
 [33 44]
 [55 66]]


In [91]:

#unary ufunc
a=np.arange(10)
print(a)
print("\n")
print(np.round_(np.sqrt(a),2))
print("-----")
print(np.exp(a))
print("----")

#binary ufunc

#np.maximum computes element wise maximum

#fmax ignores NaN
a=np.random.randn(8)
b=np.random.randn(8)
print(a)
print("\n")
print(b)
print("\n")
print(np.maximum(a,b))

#modf returns the fractional and integral parts of floating point array

a=np.random.randn(5)*5
print(a)
print('------\n')
rem,whole=np.modf(a)
print(rem)
print(whole)

[0 1 2 3 4 5 6 7 8 9]


[0.   1.   1.41 1.73 2.   2.24 2.45 2.65 2.83 3.  ]
-----
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
----
[ 3.04649197  0.55815969 -0.97074455  0.14571342 -1.1409859   1.27488432
  0.70286475 -0.70400927]


[-1.51474184 -0.40229247  1.54199787 -1.0951092   0.26887289  0.43106821
 -0.18238634 -0.51830345]


[ 3.04649197  0.55815969  1.54199787  0.14571342  0.26887289  1.27488432
  0.70286475 -0.51830345]
[ 5.7166072   5.83012781 -1.92047213 -4.13045886 -5.35947217]
------

[ 0.7166072   0.83012781 -0.92047213 -0.13045886 -0.35947217]
[ 5.  5. -1. -4. -5.]


In [92]:
#mathematical and statistical methods
#use aggregations like sum, mean and std either by calling the array instance method or using the top-level numPy function.

a=np.random.randn(5,4)
print(a.mean())
print(np.mean(a))
print(np.sum(a))

# mean and sum take an optyional axis argument that computes the statistic over the given axis, resulting in an array with one fewer dimension
a.mean(axis=1)
a.sum(axis=0)

a = np.array([1,0,2,-3,6,8,4,7])
b = np.array([[3,6],[4,2]])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(b.mean(axis=0))
print(a.std())
print(b.std(axis=0))
#mathematical and statistical methods
#use aggregations like sum, mean and std either by calling the array instance method or using the top-level numPy function.

a=np.random.randn(5,4)
print(a.mean())
print(np.mean(a))
print(np.sum(a))

# mean and sum take an optyional axis argument that computes the statistic over the given axis, resulting in an array with one fewer dimension
a.mean(axis=1)
a.sum(axis=0)

-0.032057368515326624
-0.032057368515326624
-0.6411473703065325
8
-3
25
3.125
[3.5 4. ]
3.550968177835448
[0.5 2. ]
-0.29979036793104413
-0.29979036793104413
-5.995807358620882


array([ 1.29240705,  0.59486525, -6.06901991, -1.81405975])

In [95]:
#Broadcasting

# It describes how NumPy treats arrays with different shapes during arithmetic operations 
# subject to certain constraints the smaller array is "broadcast " across the large array so that they have 
# compatible shapes


import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
b=2
print(a+b)

[[3 4]
 [5 6]
 [7 8]]


In [101]:
#Broadcasting
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([1,2,3,4])
c=7
d=np.array([8])
e = np.array([7,2])
print(a+e)
print(a.shape,b.shape,d.shape)
#print(a+b)
print(a+c)
print(a+d)

[[ 8  4]
 [10  6]
 [12  8]]
(3, 2) (4,) (1,)
[[ 8  9]
 [10 11]
 [12 13]]
[[ 9 10]
 [11 12]
 [13 14]]


In [113]:
#Broadcasting
import numpy as np
#a=np.array([[1,2],[3,4],[5,6]])
a=np.array([1,2,3,4])
#b=np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
#b=np.array([[1],[2],[3]])
b=np.array([[1],[2],[3],[4]])
print(a.ndim,b.ndim)
print(a.shape,b.shape)
print(a+b)

1 2
(4,) (4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [105]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print('\n No of dimensions = ',a.ndim,'\n',
       'shape =', a.shape,'\n',
       'size = ', a.size,'\n',
       'data type = ',a.dtype,'\n',
       'size of element = ',a.itemsize,'\n',
       'total size= ',a.nbytes)
for i in range(a.size):
    print(id(a[i]))
    
print("------")
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
for i in range(3):
    for j in range(2):
        print(id(a[i]))
        

[1 2 3 4 5]

 No of dimensions =  1 
 shape = (5,) 
 size =  5 
 data type =  int32 
 size of element =  4 
 total size=  20
2134580991984
2134580995792
2134580991984
2134580995792
2134580991984
------
2134582206192
[1 2]
2134582206192
[1 2]
2134582206192
[3 4]
2134582206192
[3 4]
2134582206192
[5 6]
2134582206192
[5 6]


In [106]:
#splitting arrays
import numpy as np
a=np.arange(1,25).reshape(12,2)
print(a, a.ndim,a.size,a.shape)
print('\n  vsplit  \n')
#hsplit -  split into equally shaped arrays
print(np.vsplit(a,3))

print('\n  vsplit  \n')
print(np.vsplit(a,(3,4)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]] 2 24 (12, 2)

  vsplit  

[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]]), array([[17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])]

  vsplit  

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[7, 8]]), array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])]


In [121]:
#stacking arrays

print("To create an array from existing data: Indexing, Slicing, hstack, vstack, hsplit, view, copy ")

print("\n")

v1 = np.arange(1,10,2)
print(v1)
v2 = np.arange(10,20,2)
print(v2)
print("stacking vertically:  ",np.vstack((v1,v2))) # no.of elements must be same in two arrays

h1 = np.ones(v1.shape)
print(h1)
h2 = np.zeros(v2.shape)
print(h2)
print("Stacking Horizontally: ",np.hstack((h1,h2)))

a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
print(a1,a2)
print('\n vstack \n')
print(np.vstack((a1,a2)))
print('\n hstack \n')
print(np.hstack((a1,a2)))

To create an array from existing data: Indexing, Slicing, hstack, vstack, hsplit, view, copy 


[1 3 5 7 9]
[10 12 14 16 18]
stacking vertically:   [[ 1  3  5  7  9]
 [10 12 14 16 18]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
Stacking Horizontally:  [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
[[1 1]
 [2 2]] [[3 3]
 [4 4]]

 vstack 

[[1 1]
 [2 2]
 [3 3]
 [4 4]]

 hstack 

[[1 1 3 3]
 [2 2 4 4]]


In [108]:
#sorting
a=np.array([10,6,3,8,2,1,7,5])
print(np.sort(a))
a=np.array([[1,4],[3,2]])
print(a)
print('\n  axis = None \n')
      
print(np.sort(a,axis=None))

print('\n  axis = 0 \n')
print(np.sort(a))

print('\n  axis = 1 \n')
b=np.array([[9,4],[13,2]])
print('\n array \n')
print(b,'\n')
print(np.sort(b,axis=1))

[ 1  2  3  5  6  7  8 10]
[[1 4]
 [3 2]]

  axis = None 

[1 2 3 4]

  axis = 0 

[[1 4]
 [2 3]]

  axis = 1 


 array 

[[ 9  4]
 [13  2]] 

[[ 4  9]
 [ 2 13]]


In [109]:
#Reverse an array
a=[9,2,5,1,8,4]
print(np.flip(a))
#Reverse only rows or only columns
a=[[3,9,5],[6,2,4]]
print(np.flip(a))
print(np.flip(a,axis=0))
print(np.flip(a,axis=1))

[4 8 1 5 2 9]
[[4 2 6]
 [5 9 3]]
[[6 2 4]
 [3 9 5]]
[[5 9 3]
 [4 2 6]]


In [110]:
#flatten
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.flatten()

print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [111]:
#Searchsorted - performs a binary search and returns the index 
#where the specified value would be inserted
a=[2,4,7,9,12,15,17]
b=np.searchsorted(a,7)
print(b)
b=np.searchsorted(a,7,side='right')
print(b)

2
3


In [112]:
#how to make numpy array immutable
a=np.array([1,2,3,4,5])
a[0]=99
print(a)
a.setflags(write=False)
a[0]=88
print(a)

[99  2  3  4  5]


ValueError: assignment destination is read-only